### ISSUE TITLE
--user argument

### ISSUE THREAD

**Issue by vreinharz** [defjaf/pip_upgrade_outdated#3]
Great script, but on my  Ubuntu computer where all my packages are installed with the --user flag it fails. 

By hard coding it in the script it works perfectly, would it be possible to just add a flag for that case? 

I tried to add a pull request for that feature: #4

**Comment by defjaf** [comment]
Thanks for the PR -- I've never actually merged one before, but I'll try ASAP!

**Comment by vreinharz** [comment]
Glad to hear that! It's my first try to propose a PR.
I tried to follow your style, let me know if I can do any modifications!
